### PR TITLE
Feature/rpi support

### PR DESCRIPTION
**Pull request by avilleret**
This PR allow to build on Raspberry PI.
But it might fail on other Arm devices since there is no device detection mechanism and it assumes some things like : 
- arm use OpenGLES and EGL instead of OpenGL, GLEW and GLFW
- arm has some lib like vcos, OpenMaxIL and other, which is indeed wrong and works only for the Pi.

There is a TargetArch.cmake which should return the arch we are targetting.
But this is redundant with openFrameworks platform detection system (and work the same way).

So this is not perfect, but seems to work for native build with make.
Ninja build on RPi doesn't work yet and I don't know Ninja enough to understand why.
Maybe we should use the PLATFORM_VARIANT variable to define the board instead of trying to guess anything.
I will try cross building when I have time.

### CODE REVIEW

**Comment by procedural** [comment]
Cool! But first, let the review process begin! :D

**Comment by avilleret** [comment]
A quick test this morning shows that building of on RPi requires jessie (the official distro is still based on Wheezy)

**Comment by procedural** [comment]
>A quick test this morning shows that building of on RPi requires jessie

Why so?

**Comment by avilleret** [comment]
gcc 4.9, clang-3.6 and ninja-build are not available in the wheezy repo
rather than trying to get them working on Wheezy I think it's easier to upgrade system and use current stable debian distro (jessie).

**Comment by avilleret** [comment]
clang-3.6 is not yet available on jessie, should we use nighlty build ? from http://llvm.org/apt/ ?

**Comment by procedural** [comment]
@avilleret does it have clang 3.5?

**Comment by procedural** [comment]
I mean, does jessie have clang 3.5 by default, without enabling llvm's ppa?

**Comment by avilleret** [comment]
yes there is clang-3.5 in the Jessie's repo
And I found 3.6.2 release binary on llvm.org that seems to work.
So I updated the intsall sript to use that

**Comment by procedural** [comment]
>And I found 3.6.2 release binary on llvm.org that seems to work.

I don't want to use it, thought, since LLVM's PPA caused broken packages on few of my setups a while ago, also they have no sanitizer libraries compiled there so we should really stick to system's Clang 3.5.

**Comment by avilleret** [comment]
ok, I thought by mistake that you want to use 3.6, I'll roll back in few minutes

**Comment by procedural** [comment]
>I thought by mistake that you want to use 3.6

Sorry, didn't communicated what I wanted. -- latest availabe system version of Clang, basically... In our case it will be Clang 3.5.

**Comment by procedural** [comment]
It seems like fixing #15 caused branch to be unmergeable. Could you rebase it to latest commit?

**Comment by avilleret** [comment]
Done !

**Comment by procedural** [comment]
Last few questions before merge :)

Did you tested it on Raspberry Pi or Raspberry Pi 2?

Do you agree to merge this code under MIT license?

**Comment by avilleret** [comment]
> Did you tested it on Raspberry Pi or Raspberry Pi 2?

RPi2 only for now

> Do you agree to merge this code under MIT license?

yes

**Comment by procedural** [comment]
@avilleret I merged it! Thank you for this PR!

I'll change `PLATFORM_VARIANT` as discussed above and tweak it a little to match style of the project.

Thanks again!

**Comment by avilleret** [comment]
thanks for merging it !

**Pull request merged**
